# Generated by Django 3.2.8 on 2021-10-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatigoryDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='category')),
            ],
            options={
                'verbose_name': 'категория блюд',
                'verbose_name_plural': 'категории блюд',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catigorydish', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
    ]
