# Generated by Django 3.2.8 on 2021-11-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
