# Generated by Django 3.2.8 on 2021-10-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catigorydish_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatigoryPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='category')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категория портфолио',
                'verbose_name_plural': 'категории портфолио',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='название')),
                ('small_image', models.ImageField(upload_to='static/image', verbose_name='маленькая картинка')),
                ('large_image', models.ImageField(upload_to='static/image', verbose_name='маленькая картинка')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.catigoryportfolio')),
            ],
            options={
                'verbose_name': 'портфолио',
                'verbose_name_plural': 'портфолио',
            },
        ),
    ]
