# Generated by Django 3.2.8 on 2021-11-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Contact',
        ),
    ]
