# Generated by Django 3.2.8 on 2021-11-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_catigoryportfolio_portfolio'),
        ('main', '0007_auto_20211118_2258'),
    ]

    operations = [
    ]
